// Registre des articles du blog RenoHab (du plus récent au plus ancien).
//
// ➜ POUR AJOUTER UN ARTICLE : insérer une nouvelle entrée EN TÊTE de ce tableau.
//    Elle alimente automatiquement :
//      - la page /blog (liste complète),
//      - la section "Ressources & conseils" de l'accueil (6 derniers articles),
//      - les vignettes optimisées générées au build (scripts/make-blog-thumbs.mjs).
//    La route React (App.js) et public/sitemap.xml restent à ajouter séparément.
//
// Champs :
//   slug    : segment d'URL après /blog/ (doit correspondre à la route dans App.js)
//   title   : titre affiché sur la carte
//   excerpt : 1 à 2 phrases de résumé
//   tag     : thème court (ex. "Aides", "Chauffage", "Isolation")
//   date    : date de publication, format court FR (ex. "15 sept. 2026")
//   image   : chemin public de l'image (en général /blog/<slug>.jpg)
//   alt     : texte alternatif de l'image

export const ARTICLES = [
  {
    slug: "chaudiere-gaz-2026-remplacement-cout",
    title: "Chaudière à gaz en 2026 : encore légale mais sans aide — ce que ça coûte vraiment",
    excerpt: "Remplacer une chaudière à gaz reste autorisé, mais sans MaPrimeRénov', CEE ni TVA réduite. Le vrai coût, et les alternatives subventionnées.",
    tag: "Chauffage",
    date: "23 sept. 2026",
    image: "/blog/chaudiere-gaz-2026-remplacement-cout.jpg",
    alt: "Chaudière à gaz murale dans un logement en cours de rénovation",
  },
  {
    slug: "loi-relance-logement-passoires-thermiques-bailleurs-2026",
    title: "Passoires thermiques : la Loi Relance Logement change-t-elle vraiment les règles ?",
    excerpt: "Le Sénat a adopté en juillet 2026 un texte pour assouplir l'interdiction de louer les logements F et G. Ce qu'il prévoit, ce qui reste incertain, et pourquoi rénover maintenant reste la meilleure stratégie.",
    tag: "Bailleurs",
    date: "21 sept. 2026",
    image: "/blog/loi-relance-logement-passoires-thermiques-bailleurs-2026.jpg",
    alt: "Étiquette DPE passoire thermique – loi relance logement 2026 et interdiction de location",
  },
  {
    slug: "isolation-toiture-terrasse-2026",
    title: "Isolation de la toiture-terrasse en 2026 : techniques, aides et retour sur investissement",
    excerpt: "Toiture-terrasse inaccessible, accessible ou végétalisée : les techniques adaptées, les aides 2026 (MaPrimeRénov', CEE, TVA 5,5 %) et le financement.",
    tag: "Isolation",
    date: "20 sept. 2026",
    image: "/blog/isolation-toiture-terrasse-2026.jpg",
    alt: "Toiture-terrasse d'une maison moderne avec isolation thermique",
  },
  {
    slug: "plancher-chauffant-pac-basse-temperature-2026",
    title: "Plancher chauffant + PAC : le duo gagnant pour réduire vos factures en 2026",
    excerpt: "Associer une pompe à chaleur à un plancher chauffant basse température maximise le confort et le rendement. Fonctionnement, coûts et aides disponibles.",
    tag: "Chauffage",
    date: "15 sept. 2026",
    image: "/blog/plancher-chauffant-pac-basse-temperature-2026.jpg",
    alt: "Plancher chauffant basse température et pompe à chaleur dans une maison rénovée",
  },
  {
    slug: "renovation-energetique-residence-secondaire-2026",
    title: "Résidence secondaire : quelles aides à la rénovation énergétique en 2026 ?",
    excerpt: "MaPrimeRénov' est réservée aux résidences principales, mais CEE, éco-PTZ et TVA 5,5 % restent accessibles. Le point sur ce qui finance une maison de vacances.",
    tag: "Aides",
    date: "13 sept. 2026",
    image: "/blog/renovation-energetique-residence-secondaire-2026.jpg",
    alt: "Maison de vacances en France bénéficiant d'une rénovation énergétique",
  },
  {
    slug: "maprimerenov-2027-maisons-dpe-fg-ce-qui-change",
    title: "Maisons F ou G : l'échéance MaPrimeRénov' reportée au 1er janvier 2028",
    excerpt: "Le décret du 25 août 2026 laisse aux maisons F et G l'accès aux aides par geste jusqu'au 31 décembre 2027 (DPE exigé en 2028). Ce que ça change, et pourquoi agir maintenant.",
    tag: "Aides",
    date: "12 sept. 2026",
    image: "/blog/maprimerenov-2027-maisons-dpe-fg-ce-qui-change.jpg",
    alt: "Étiquette DPE F ou G sur une maison ancienne – réforme MaPrimeRénov' 2027",
  },
  {
    slug: "agrement-pac-prime-cee-bonifiee-septembre-2026",
    title: "Prime CEE PAC : l'agrément obligatoire depuis le 1er septembre 2026",
    excerpt: "Depuis le 1er septembre, seules les PAC agréées donnent accès à la prime CEE bonifiée. Vérifiez votre modèle sur la liste ADEME avant de signer.",
    tag: "Aides",
    date: "11 sept. 2026",
    image: "/blog/agrement-pac-prime-cee-bonifiee-septembre-2026.jpg",
    alt: "Agrément PAC prime CEE bonifiée : pompe à chaleur agréée ADEME depuis septembre 2026",
  },
  {
    slug: "entretien-pompe-a-chaleur-pac-2026",
    title: "Entretien PAC 2026 : obligations, fréquence et prix",
    excerpt: "À quelle fréquence faire entretenir sa pompe à chaleur ? Quelles obligations F-Gaz ? Combien ça coûte ? Tout ce que vous devez savoir avant l'hiver.",
    tag: "Maintenance",
    date: "10 sept. 2026",
    image: "/blog/entretien-pompe-a-chaleur-pac-2026.jpg",
    alt: "Entretien pompe à chaleur : technicien en maintenance PAC extérieure",
  },
  {
    slug: "pret-avance-renovation-par-2026",
    title: "PAR et PAR+ 2026 : rénover sans avancer l'argent",
    excerpt: "0 % d'intérêt pendant 10 ans pour les ménages modestes, pas de mensualités pendant toute la détention du bien : le Prêt Avance Rénovation est une alternative méconnue à l'Éco-PTZ.",
    tag: "Financement",
    date: "9 sept. 2026",
    image: "/blog/pret-avance-renovation-par-2026.jpg",
    alt: "Prêt Avance Rénovation PAR et PAR+ : financer sans avance de fonds",
  },
  {
    slug: "thermostat-programmable-regulation-chauffage-2026",
    title: "Thermostat programmable en 2026 : économies, obligation et aides disponibles",
    excerpt: "-7 % par degré économisé, obligation légale reportée à 2030, CEE BAR-TH-173 encore actif : tout savoir sur la régulation du chauffage cette année.",
    tag: "Régulation",
    date: "8 sept. 2026",
    image: "/blog/thermostat-programmable-regulation-chauffage-2026.jpg",
    alt: "Thermostat programmable : économies, obligation et aides 2026",
  },
  {
    slug: "pompe-a-chaleur-air-air-reversible-aides-2026",
    title: "PAC air/air réversible : aides, prix et conditions en 2026",
    excerpt: "Prime CEE jusqu'à 975 €, TVA à 5,5 % depuis juillet 2026 : tout ce que vous devez savoir sur le split réversible avant de vous lancer.",
    tag: "Chauffage",
    date: "7 sept. 2026",
    image: "/blog/pompe-a-chaleur-air-air-reversible-aides-2026.jpg",
    alt: "Pompe à chaleur air/air réversible : aides 2026",
  },
  {
    slug: "chauffe-eau-solaire-individuel-cesi-2026",
    title: "CESI en 2026 : quelles aides après la réforme de septembre ?",
    excerpt: "MaPrimeRénov' par geste ne finance plus le chauffe-eau solaire depuis le 1er septembre 2026. CEE, TVA 5,5 %, Éco-PTZ : voici ce qui reste et si le CESI est encore rentable.",
    tag: "Eau chaude sanitaire",
    date: "6 sept. 2026",
    image: "/blog/chauffe-eau-solaire-individuel-cesi-2026.jpg",
    alt: "Chauffe-eau solaire individuel CESI : aides 2026",
  },
  {
    slug: "passoire-thermique-vendre-ou-renover-2026",
    title: "Passoire thermique : vendre ou rénover en 2026 ?",
    excerpt: "Logement F ou G : décote à la vente, interdiction de louer, aides jusqu'à 40 000 €… On compare les deux options chiffres à l'appui pour vous aider à choisir.",
    tag: "Stratégie patrimoine",
    date: "5 sept. 2026",
    image: "/blog/passoire-thermique-vendre-ou-renover-2026.jpg",
    alt: "Passoire thermique : faut-il vendre ou rénover en 2026 ?",
  },
  {
    slug: "renovation-appartement-copropriete-travaux-privatifs-2026",
    title: "Appartement en copropriété : quels travaux sans vote en AG ?",
    excerpt: "Isolation intérieure, chauffe-eau thermodynamique, VMC : ce que vous pouvez faire seul dans votre partie privative, les aides disponibles et ce qui nécessite un vote en assemblée générale.",
    tag: "Copropriété",
    date: "4 sept. 2026",
    image: "/blog/renovation-appartement-copropriete-travaux-privatifs-2026.jpg",
    alt: "Rénovation énergétique en appartement copropriété : travaux privatifs 2026",
  },
  {
    slug: "maprimerenov-proprietaire-bailleur-2026",
    title: "MaPrimeRénov' bailleur 2026 : toutes les aides pour votre logement locatif",
    excerpt: "Interdiction de louer les passoires G depuis janvier 2025, fin du monogeste en septembre 2026 : ce que chaque propriétaire bailleur doit savoir pour rénover et maintenir son bien en location.",
    tag: "Aides & financement",
    date: "3 sept. 2026",
    image: "/blog/maprimerenov-proprietaire-bailleur-2026.jpg",
    alt: "MaPrimeRénov' propriétaire bailleur 2026 : aides, conditions et démarches",
  },
  {
    slug: "pompe-a-chaleur-geothermique-sol-eau-2026",
    title: "PAC géothermique sol/eau : fonctionnement, prix et aides en 2026",
    excerpt: "La pompe à chaleur géothermique affiche un COP de 3,5 à 5, sans unité extérieure et sans dépendance aux températures hivernales. Prix, capteurs horizontaux vs sondes verticales, et aides disponibles.",
    tag: "Chauffage",
    date: "2 sept. 2026",
    image: "/blog/pompe-a-chaleur-geothermique-sol-eau-2026.jpg",
    alt: "Pompe à chaleur géothermique sol/eau : fonctionnement, prix et aides en 2026",
  },
  {
    slug: "dpe-collectif-copropriete-2026",
    title: "DPE collectif en copropriété : obligations 2026, coût et démarches",
    excerpt: "Obligatoire depuis janvier 2026 pour toutes les copropriétés, le DPE collectif conditionne l'accès aux aides : MaPrimeRénov' Copro, CEE, éco-PTZ. Qui est concerné, combien ça coûte, comment l'obtenir.",
    tag: "Copropriété",
    date: "1er sept. 2026",
    image: "/blog/dpe-collectif-copropriete-2026.jpg",
    alt: "DPE collectif en copropriété : obligations 2026, coût et démarches",
  },
  {
    slug: "preparer-logement-hiver-2026-checklist",
    title: "Préparer son logement pour l'hiver 2026 : la checklist complète",
    excerpt: "Entretien chaudière obligatoire, purge des radiateurs, VMC, joints de fenêtres, ramonage : la liste des gestes indispensables à réaliser avant novembre pour chauffer efficacement et sans mauvaise surprise.",
    tag: "Chauffage",
    date: "31 août 2026",
    image: "/blog/preparer-logement-hiver-2026-checklist.jpg",
    alt: "Préparer son logement pour l'hiver 2026 : checklist travaux et entretiens",
  },
  {
    slug: "isolation-combles-amenages-sarking-2026",
    title: "Combles aménagés : Sarking, prix et aides 2026",
    excerpt: "Isolation des rampants de toiture, technique Sarking par l'extérieur ou isolation par l'intérieur : tout savoir sur les solutions, les prix et les aides disponibles (MaPrimeRénov', CEE, TVA 5,5 %).",
    tag: "Isolation",
    date: "30 août 2026",
    image: "/blog/isolation-combles-amenages-sarking-2026.jpg",
    alt: "Isolation des combles aménagés par technique Sarking en 2026",
  },
  {
    slug: "choisir-artisan-rge-2026",
    title: "Artisan RGE 2026 : comment le trouver, le vérifier et éviter les arnaques",
    excerpt: "Sans artisan RGE, pas d'aide à la rénovation : ni MaPrimeRénov', ni CEE, ni Éco-PTZ. Comment identifier le bon professionnel, vérifier sa certification et ne pas tomber dans les pièges du démarchage abusif.",
    tag: "Démarches",
    date: "29 août 2026",
    image: "/blog/choisir-artisan-rge-2026.jpg",
    alt: "Artisan RGE : comment trouver et vérifier un professionnel certifié en 2026",
  },
  {
    slug: "attestation-dpe-ademe-2026-etiquette-gratuite",
    title: "Attestation DPE ADEME 2026 : nouvelle étiquette gratuite en 5 minutes",
    excerpt: "7 millions de logements gagnent une classe DPE depuis janvier 2026. Si votre diagnostic date de 2021 à 2025, téléchargez gratuitement votre attestation officielle sur l'Observatoire ADEME — sans diagnostiqueur.",
    tag: "DPE",
    date: "28 août 2026",
    image: "/blog/attestation-dpe-ademe-2026-etiquette-gratuite.jpg",
    alt: "Attestation DPE ADEME 2026 : nouvelle étiquette gratuite en ligne",
  },
  {
    slug: "rendez-vous-france-renov-maprimerenov-2026",
    title: "RDV France Rénov' obligatoire : l'étape clé avant MaPrimeRénov' rénovation d'ampleur",
    excerpt: "Depuis février 2026, un entretien gratuit avec un conseiller France Rénov' est exigé avant tout dépôt de dossier. Comment prendre RDV, quoi préparer et obtenir l'attestation indispensable.",
    tag: "Démarches",
    date: "27 août 2026",
    image: "/blog/rendez-vous-france-renov-maprimerenov-2026.jpg",
    alt: "Rendez-vous France Rénov' obligatoire MaPrimeRénov' 2026",
  },
  {
    slug: "cee-renovation-ampleur-classes-efg-septembre-2026",
    title: "CEE rénovation d'ampleur : seuls les logements E, F, G éligibles dès le 1er septembre",
    excerpt: "L'arrêté du 17 août 2026 exclut les logements classés D de la prime CEE rénovation d'ampleur. Ce qui change, la dérogation pour les dossiers déposés avant le 1er septembre, et les aides alternatives.",
    tag: "Prime CEE",
    date: "26 août 2026",
    image: "/blog/cee-renovation-ampleur-classes-efg-septembre-2026.jpg",
    alt: "CEE rénovation d'ampleur logements E F G éligibles septembre 2026",
  },
  {
    slug: "poele-a-bois-insert-chemine-aides-2026",
    title: "Poêle à bois et insert : les aides à saisir avant le 1er septembre 2026",
    excerpt: "MaPrimeRénov' pour les poêles à bois et inserts de cheminée s'arrête le 1er septembre. Montants par revenus, label Flamme Verte, prime CEE et démarches urgentes.",
    tag: "Chauffage",
    date: "25 août 2026",
    image: "/blog/poele-a-bois-insert-chemine-aides-2026.jpg",
    alt: "Poêle à bois et insert de cheminée : aides 2026",
  },
  {
    slug: "maprimeadapt-2026-aide-adaptation-logement-seniors",
    title: "MaPrimeAdapt' 2026 : jusqu'à 70 % des travaux pour adapter votre logement",
    excerpt: "Seniors et personnes handicapées peuvent obtenir jusqu'à 15 400 € pour douche adaptée, monte-escalier, élargissement de portes… Conditions, montants et démarches.",
    tag: "Aides",
    date: "24 août 2026",
    image: "/blog/maprimeadapt-2026-aide-adaptation-logement-seniors.jpg",
    alt: "MaPrimeAdapt' 2026 : adapter son logement au vieillissement ou au handicap",
  },
  {
    slug: "chaudiere-granules-bois-aides-2026",
    title: "Chaudière à granulés 2026 : fin de MaPrimeRénov' par geste, quelles aides restent ?",
    excerpt: "Depuis le 1er janvier 2026, la chaudière biomasse n'est plus éligible au parcours monogeste. CEE, TVA 5,5 %, Éco-PTZ et rénovation d'ampleur : toutes les alternatives pour financer votre projet.",
    tag: "Chauffage",
    date: "23 août 2026",
    image: "/blog/chaudiere-granules-bois-aides-2026.jpg",
    alt: "Chaudière à granulés de bois : aides disponibles en 2026",
  },
  {
    slug: "maprimerenov-ampleur-fin-gaz-septembre-2026",
    title: "MaPrimeRénov' rénovation d'ampleur : fin du chauffage au gaz dès le 1er septembre 2026",
    excerpt: "À partir du 1er septembre, une maison individuelle ne peut plus bénéficier de la rénovation d'ampleur si elle conserve un chauffage gaz. Ce qui change, les alternatives et comment anticiper.",
    tag: "MaPrimeRénov'",
    date: "22 août 2026",
    image: "/blog/maprimerenov-ampleur-fin-gaz-septembre-2026.jpg",
    alt: "MaPrimeRénov' rénovation d'ampleur : fin du gaz au 1er septembre 2026",
  },
  {
    slug: "france-renov-compte-unique-aides-anah-2026",
    title: "Nouveau compte FranceRénov' : toutes les aides Anah en un seul endroit depuis août 2026",
    excerpt: "MaPrimeRénov', MaPrimeAdapt', Loc'Avantages… Depuis le 17 août, un compte unique sécurisé par FranceConnect+ centralise toutes les démarches. Ce qui change pour votre dossier.",
    tag: "Aides",
    date: "21 août 2026",
    image: "/blog/france-renov-compte-unique-aides-anah-2026.jpg",
    alt: "Nouveau compte FranceRénov' — toutes les aides Anah centralisées",
  },
  {
    slug: "isolation-thermique-interieure-iti-2026",
    title: "Isolation par l'intérieur (ITI) 2026 : prix, aides CEE et quand la choisir",
    excerpt: "Appartement, secteur protégé ou budget serré ? L'ITI reste finançable via les CEE, la TVA à 5,5 % et l'éco-PTZ. Toutes les règles 2026 décryptées.",
    tag: "Isolation",
    date: "20 août 2026",
    image: "/blog/isolation-thermique-interieure-iti-2026.jpg",
    alt: "Isolation thermique par l'intérieur (ITI) en 2026",
  },
  {
    slug: "cumul-aides-renovation-maprimerenov-cee-eco-ptz",
    title: "Cumuler MaPrimeRénov', CEE et Éco-PTZ en 2026 : jusqu'à 90 % de vos travaux financés",
    excerpt: "Règles de cumul, plafonds selon les revenus et ordre des démarches pour combiner les trois grandes aides de la rénovation énergétique sans perdre une prime.",
    tag: "Financement",
    date: "19 août 2026",
    image: "/blog/cumul-aides-renovation-maprimerenov-cee-eco-ptz.jpg",
    alt: "Cumuler MaPrimeRénov', CEE et Éco-PTZ en 2026",
  },
  {
    slug: "isolation-plancher-bas-vide-sanitaire-2026",
    title: "Isolation plancher bas 2026 : aides MaPrimeRénov' et CEE encore disponibles",
    excerpt: "Vide sanitaire, sous-sol non chauffé : ce geste reste éligible au parcours par geste MaPrimeRénov' et aux CEE 6e période. Prix, montants et démarches.",
    tag: "Isolation",
    date: "18 août 2026",
    image: "/blog/isolation-plancher-bas-vide-sanitaire-2026.jpg",
    alt: "Isolation du plancher bas — vide sanitaire et aides 2026",
  },
  {
    slug: "maprimerenov-coproprietes-2026",
    title: "MaPrimeRénov' Copropriétés 2026 : jusqu'à 25 000 € par logement",
    excerpt: "30 à 45 % de vos travaux collectifs financés par l'ANAH, plus bonus copropriété fragile et cumul CEE. Conditions, barèmes et nouveauté 2026.",
    tag: "Copropriétés",
    date: "17 août 2026",
    image: "/blog/maprimerenov-coproprietes-2026.jpg",
    alt: "Immeuble en copropriété — rénovation énergétique collective 2026",
  },
  {
    slug: "nouveau-calcul-dpe-2026-reclassement",
    title: "Nouveau calcul DPE 2026 : 850 000 logements changent de classe sans travaux",
    excerpt: "Le coefficient électricité passe de 2,3 à 1,9 depuis janvier 2026 : découvrez si votre logement a gagné une classe énergétique et comment obtenir l'attestation actualisée sans nouvelle visite.",
    tag: "DPE",
    date: "16 août 2026",
    image: "/blog/nouveau-calcul-dpe-2026-reclassement.jpg",
    alt: "Étiquette DPE — nouveau coefficient électricité 2026",
  },
  {
    slug: "fenetres-remplacement-aides-2026",
    title: "Remplacement des fenêtres en 2026 : toutes les aides disponibles",
    excerpt: "MaPrimeRénov', CEE, TVA à 5,5 %, Éco-PTZ : comment financer le remplacement de vos fenêtres simple vitrage et réduire vos déperditions thermiques.",
    tag: "Menuiseries",
    date: "15 août 2026",
    image: "/blog/fenetres-remplacement-aides-2026.jpg",
    alt: "Remplacement de fenêtres double vitrage — aides 2026",
  },
  {
    slug: "panneaux-solaires-photovoltaiques-aides-2026",
    title: "Panneaux solaires 2026 : quelles aides après la fin de la prime à l'autoconsommation ?",
    excerpt: "La prime à l'autoconsommation a été supprimée le 5 juin 2026. TVA à 5,5 %, CEE, éco-PTZ : ce qui reste disponible et comment rentabiliser votre installation photovoltaïque malgré ce changement.",
    tag: "Énergie solaire",
    date: "14 août 2026",
    image: "/blog/panneaux-solaires-photovoltaiques-aides-2026.jpg",
    alt: "Maison avec panneaux solaires photovoltaïques — autoconsommation 2026",
  },
  {
    slug: "renovation-maison-ancienne-2026",
    title: "Rénover une maison ancienne en 2026 : guide pratique, pièges et aides",
    excerpt: "Isolation respirante, gestion de l'humidité, MaPrimeRénov'… Les maisons d'avant 1975 obéissent à des règles spécifiques. Découvrez les techniques adaptées au bâti ancien et les aides pour financer votre rénovation en 2026.",
    tag: "Bâti ancien",
    date: "13 août 2026",
    image: "/blog/renovation-maison-ancienne-2026.jpg",
    alt: "Maison ancienne en pierre — rénovation énergétique 2026",
  },
  {
    slug: "vmc-double-flux-aides-2026",
    title: "VMC double flux 2026 : prix, aides et la règle du geste couplé à connaître",
    excerpt: "Depuis janvier 2026, la VMC double flux n'est plus finançable seule par MaPrimeRénov'. Jusqu'à 2 500 € d'aide si couplée à l'isolation, plus CEE et TVA à 5,5 %. Prix, critères techniques et stratégie pour maximiser vos subventions.",
    tag: "Ventilation",
    date: "12 août 2026",
    image: "/blog/vmc-double-flux-aides-2026.jpg",
    alt: "Installation VMC double flux — ventilation mécanique contrôlée maison",
  },
  {
    slug: "isolation-murs-exterieure-ite-2026",
    title: "ITE 2026 : isolation des murs par l'extérieur — prix, aides et démarches",
    excerpt: "Traiter jusqu'à 25 % des déperditions sans perdre de surface habitable. En 2026, MaPrimeRénov' ITE passe uniquement par le Parcours accompagné. Coûts, CEE, éco-PTZ et étapes clés du chantier expliqués.",
    tag: "Isolation",
    date: "11 août 2026",
    image: "/blog/isolation-murs-exterieure-ite-2026.jpg",
    alt: "Isolation thermique par l'extérieur — chantier ITE sur maison individuelle",
  },
  {
    slug: "sortir-du-fioul-2026-alternatives-aides",
    title: "Sortir du fioul en 2026 : alternatives, aides et démarches pour changer de chauffage",
    excerpt: "Chaudière fioul interdite depuis 2022, jusqu'à 9 000 € d'aides cumulables (MaPrimeRénov' + CEE Coup de pouce + éco-PTZ). PAC air/eau, granulés, hybride : toutes les alternatives et les étapes pour agir.",
    tag: "Chauffage",
    date: "10 août 2026",
    image: "/blog/sortir-du-fioul-2026-alternatives-aides.jpg",
    alt: "Remplacement chaudière fioul — transition chauffage propre",
  },
  {
    slug: "isolation-combles-perdus-2026",
    title: "Isolation des combles perdus : agissez avant septembre pour cumuler MaPrimeRénov' et CEE",
    excerpt: "MaPrimeRénov' monogeste pour les combles disparaît le 1er septembre 2026. Jusqu'à 75 €/m² d'aides pour les ménages modestes, CEE cumulables, TVA à 5,5 % : tout ce qu'il faut savoir avant la date limite.",
    tag: "Urgence",
    date: "9 août 2026",
    image: "/blog/isolation-combles-perdus-2026.jpg",
    alt: "Isolation des combles perdus — laine soufflée dans des combles",
  },
  {
    slug: "ordre-travaux-renovation-energetique-2026",
    title: "Dans quel ordre faire ses travaux de rénovation énergétique en 2026 ?",
    excerpt: "Isoler d'abord, changer le chauffage ensuite : suivez la bonne séquence de travaux pour maximiser vos aides MaPrimeRénov', éviter les reprises et atteindre le saut de classes DPE qui débloque les financements les plus élevés.",
    tag: "Guide pratique",
    date: "8 août 2026",
    image: "/blog/ordre-travaux-renovation-energetique-2026.jpg",
    alt: "Dans quel ordre faire ses travaux de rénovation énergétique en 2026",
  },
  {
    slug: "chauffe-eau-thermodynamique-aides-2026",
    title: "Chauffe-eau thermodynamique 2026 : prix, aides et économies",
    excerpt: "Le CET consomme 3 fois moins qu'un chauffe-eau classique. Découvrez les aides cumulables en 2026 (MaPrimeRénov', CEE, TVA 5,5 %, Éco-PTZ) et comment choisir le bon modèle pour votre logement.",
    tag: "Équipement & économies",
    date: "7 août 2026",
    image: "/blog/chauffe-eau-thermodynamique-aides-2026.jpg",
    alt: "Chauffe-eau thermodynamique 2026 — aides et économies",
  },
  {
    slug: "tva-5-5-renovation-energetique-2026",
    title: "TVA à 5,5 % rénovation 2026 : travaux éligibles et démarches simplifiées",
    excerpt: "Sans condition de ressources, la TVA à 5,5 % s'applique à tous vos travaux de rénovation énergétique. Depuis la suppression du Cerfa, une simple mention sur le devis suffit — voici comment en profiter et combien vous économisez.",
    tag: "Aides & financement",
    date: "6 août 2026",
    image: "/blog/tva-5-5-renovation-energetique-2026.jpg",
    alt: "TVA 5,5 % rénovation énergétique 2026",
  },
  {
    slug: "aides-regionales-renovation-energetique-2026",
    title: "Aides régionales rénovation 2026 : les primes méconnues à cumuler avec MaPrimeRénov'",
    excerpt: "Hauts-de-France, Nouvelle-Aquitaine, PACA, Grand Est… votre région propose peut-être des subventions supplémentaires qui s'ajoutent aux aides nationales. Guide complet du cumul pour 2026.",
    tag: "Aides & financement",
    date: "5 août 2026",
    image: "/blog/aides-regionales-renovation-energetique-2026.jpg",
    alt: "Aides régionales rénovation énergétique 2026",
  },
  {
    slug: "renovation-ampleur-2026-accompagnateur-renov",
    title: "Rénovation d'ampleur 2026 : jusqu'à 80 % de vos travaux financés",
    excerpt: "Saut de 2 classes DPE, Accompagnateur Rénov' obligatoire, taux d'aide de 80 à 10 % selon vos revenus : tout ce qu'il faut savoir avant de lancer votre projet de rénovation globale.",
    tag: "Aides & financement",
    date: "4 août 2026",
    image: "/blog/renovation-ampleur-2026-accompagnateur-renov.jpg",
    alt: "Rénovation d'ampleur 2026 — jusqu'à 80 % de travaux financés",
  },
  {
    slug: "audit-energetique-obligatoire-vente-2026",
    title: "Audit énergétique obligatoire à la vente : ce que vous devez savoir en 2026",
    excerpt: "Classes E, F et G : l'audit réglementaire est obligatoire avant de vendre votre maison. Qui est concerné, quel prix, et comment en faire un levier d'aides.",
    tag: "Réglementation",
    date: "3 août 2026",
    image: "/blog/audit-energetique-obligatoire-vente-2026.jpg",
    alt: "Audit énergétique obligatoire à la vente en 2026",
  },
  {
    slug: "maprimerenov-septembre-2026-gestes-suppression",
    title: "MaPrimeRénov' : ce qui disparaît au 1er septembre 2026",
    excerpt: "Combles, fenêtres, VMC, chauffe-eau thermodynamique : cinq gestes quittent le parcours monogeste le 1er septembre. Ce qu'il faut faire avant la date limite.",
    tag: "Aides & financement",
    date: "2 août 2026",
    image: "/blog/maprimerenov-septembre-2026-gestes-suppression.jpg",
    alt: "MaPrimeRénov' — ce qui disparaît au 1er septembre 2026",
  },
  {
    slug: "eco-ptz-2026-pret-taux-zero-renovation",
    title: "Éco-PTZ 2026 : financer sa rénovation sans payer d'intérêts",
    excerpt: "Jusqu'à 50 000 € sans intérêts, sans conditions de revenus : l'éco-prêt à taux zéro est le complément idéal de MaPrimeRénov'. Montants, conditions, démarches et exemple chiffré.",
    tag: "Aides & financement",
    date: "1er août 2026",
    image: "/blog/eco-ptz-2026-pret-taux-zero-renovation.jpg",
    alt: "Éco-PTZ 2026 — prêt à taux zéro rénovation",
  },
  {
    slug: "cee-2026-prime-energie-comment-en-profiter",
    title: "Prime CEE 2026 : comment profiter des Certificats d'Économie d'Énergie",
    excerpt: "6ème période en vigueur, nouvelle doctrine juillet 2026 : tout ce qu'il faut savoir pour obtenir votre prime énergie sans conditions de revenus et la cumuler avec MaPrimeRénov'.",
    tag: "Aides & financement",
    date: "31 juil. 2026",
    image: "/blog/cee-2026-prime-energie-comment-en-profiter.jpg",
    alt: "Prime CEE 2026 — certificats d'économie d'énergie",
  },
  {
    slug: "dpe-2026-passoires-thermiques-location",
    title: "DPE 2026 : 850 000 logements reclassés et nouvelles règles de location",
    excerpt: "Coefficient électricité abaissé, projet de loi Lecornu sur les passoires F et G, audit obligatoire à la vente : tout ce qui change pour les propriétaires en 2026.",
    tag: "DPE & réglementation",
    date: "30 juil. 2026",
    image: "/blog/dpe-2026-passoires-thermiques-location.jpg",
    alt: "DPE 2026 — passoires thermiques et location",
  },
  {
    slug: "canicule-aides-climatisation-2026",
    title: "Canicule 2026 : quelles aides pour climatiser son logement ?",
    excerpt: "La clim de confort n'est pas subventionnée : on fait le point sur les CEE, la TVA réduite, la PAC réversible et les vraies solutions pour un logement frais.",
    tag: "Confort d'été & aides",
    date: "30 juin 2026",
    image: "/blog/canicule-aides-climatisation-2026.jpg",
    alt: "Climatisation et confort d'été",
  },
  {
    slug: "pompe-a-chaleur-air-eau-prix-aides-2026",
    title: "Pompe à chaleur air/eau en 2026 : prix, aides et rentabilité",
    excerpt: "Combien coûte une PAC air/eau en 2026 ? Prix, MaPrimeRénov', CEE, TVA à 5,5 % et reste à charge : le point pour calculer la rentabilité de votre projet.",
    tag: "Chauffage & aides",
    date: "30 juin 2026",
    image: "/blog/pompe-a-chaleur-air-eau-prix-aides-2026.jpg",
    alt: "Pompe à chaleur air/eau devant une maison",
  },
  {
    slug: "valorisation-immobiliere-renovation-energetique",
    title: "Valoriser son patrimoine immobilier en 2026 : la rénovation énergétique comme levier",
    excerpt: "En 2026, la performance énergétique n'est plus un détail : c'est l'un des principaux critères de valeur d'un logement. Tour d'horizon des leviers pour valoriser un bien.",
    tag: "Conseils patrimoine",
    date: "18 juin 2026",
    image: "/DALL-E-2-maison.webp",
    alt: "Maison rénovée et valorisée",
  },
];

/** Vignette optimisée, générée au build dans public/blog/thumbs/ (voir scripts/make-blog-thumbs.mjs). */
export const articleThumb = (article) => `/blog/thumbs/${article.slug}.webp`;

/** URL de la page article. */
export const articlePath = (article) => `/blog/${article.slug}`;
